" ================
" === Pathogen ===
" ================

execute pathogen#infect()
execute pathogen#helptags()
syntax on
filetype plugin indent on

" ===================
" === Colorscheme ===
" ===================

colorscheme agnostic

" ====================
" === .vimrc.after ===
" ====================
"
" Reference <http://blog.sanctum.geek.nz/local-vimrc-files/>

if filereadable(glob("~/.vimrc.after"))
  source ~/.vimrc.after
endif
