#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

HOME_DIR=$1

if [[ -z "${HOME_DIR}" ]]; then
  echo "The home dir must be passed, aborting."
  exit 1
fi

source "${CURRDIR}/utils.sh"

ensure_vim_dir_structure

if has_pathogen; then
  echo "pathogen.vim is already installed"
else
  install_pathogen
fi


backup_copy "${HOME_DIR}/.vimrc"
printf "[symlink] " && ln -sfv "${HOME_DIR}/.vim/bundle/bouncing-vim/rc-files/vimrc" "${HOME_DIR}/.vimrc"

backup_copy "${HOME_DIR}/.tmux.conf"
printf "[symlink] " && ln -sfv "${HOME_DIR}/.vim/bundle/bouncing-vim/rc-files/tmux.conf" "${HOME_DIR}/.tmux.conf"
