#!/usr/bin/env bash

set -e

HOME_DIR=$1
CURRDIR=$(cd "$(dirname $0)" && pwd -P)
source "${CURRDIR}/config.sh"
source "${CURRDIR}/utils.sh"

"${CURRDIR}/noprompt-base" "${HOME_DIR}"

for github_project in ${ESSENTIALS[@]}; do
  clone_to_bundle_with_home "${github_project}" "${HOME_DIR}"
done

for github_project in ${NICE_TO_HAVES[@]}; do
  clone_to_bundle_with_home "${github_project}" "${HOME_DIR}"
done

echo "${NO_PROMPT_FINAL_MESSAGE}"
