#!/usr/bin/env bash

set -e

CURRDIR=$(cd "$(dirname $0)" && pwd -P)

source "${CURRDIR}/utils.sh"
source "${CURRDIR}/config.sh"

"${CURRDIR}/essential"

for plugin in ${NICE_TO_HAVES[@]}; do
  install_plugin_with_pathogen "$plugin"
done
